name: Publish (Release)

on:
  release:
    types: [published]

jobs:
  build:
    if: ${{ !github.event.release.prerelease }}
    strategy:
      matrix:
        include:
          - configuration: Release
            architecture: x64
          - configuration: Release
            architecture: ARM64
      fail-fast: false

    uses: ./.github/workflows/reusable-build.yml
    with:
      configuration: ${{ matrix.configuration }}
      architecture: ${{ matrix.architecture }}
    secrets: inherit

  changelog:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ !github.event.release.prerelease }}
    steps:
      - name: Checkout all
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Generate changelog
        run: git-cliff

      - name: Add changelog to release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rename_and_release:
    needs: [build, changelog]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - configuration: Release
            architecture: x64
          - configuration: Release
            architecture: ARM64
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: PCL2_CE_${{ matrix.configuration }}_${{ matrix.architecture }}
          path: ./artifact

      - name: Rename binaries
        run: |
          mv "./artifact/Plain Craft Launcher 2.exe" "PCL2_CE_${{ matrix.configuration }}_${{ matrix.architecture }}.exe"

      - name: Upload binary to Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: |
            PCL2_CE_${{ matrix.configuration }}_${{ matrix.architecture }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger MirrorChyanUploading
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_uploading.yml -f channel=stable -f arch=${{ matrix.architecture == 'x64' && 'x64' || 'arm64' }}
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release_note.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}